version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      pip-deps:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
    groups:
      github-actions-deps:
        patterns: ["*"]
